name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub SignIn
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
    - name: Build the Docker image
      run: docker build . --tag raibtoffoletto/excerpta:$GITHUB_REF
    - name: Push the Docker image
      run: docker push raibtoffoletto/excerpta:$GITHUB_REF
